create table game_room (
  id varchar(64) primary key,
  code varchar(16) not null unique,
  status varchar(16) not null,
  created_at timestamp with time zone not null,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  current_bandit_theme varchar(64),
  pause_reason varchar(64),
  winner_player_id varchar(64),
  version bigint not null
);

create table game_player (
  id varchar(64) primary key,
  room_id varchar(64) not null references game_room(id) on delete cascade,
  name varchar(64) not null,
  seat_order integer not null,
  connected boolean not null,
  created_at timestamp with time zone not null,
  session_token varchar(128) not null,
  device_type varchar(16) not null
);

create unique index ux_game_player_room_seat on game_player(room_id, seat_order);

create table tile (
  id varchar(64) primary key,
  room_id varchar(64) not null references game_room(id) on delete cascade,
  kind varchar(16) not null,
  face_value varchar(8),
  assigned_letter varchar(8),
  owner_player_id varchar(64),
  location varchar(16) not null,
  bag_position integer
);

create table rack_entry (
  id varchar(64) primary key,
  player_id varchar(64) not null references game_player(id) on delete cascade,
  tile_id varchar(64) not null unique references tile(id) on delete cascade,
  position integer not null
);

create unique index ux_rack_entry_player_position on rack_entry(player_id, position);

create table board_cell (
  id varchar(64) primary key,
  player_id varchar(64) not null references game_player(id) on delete cascade,
  x integer not null,
  y integer not null,
  tile_id varchar(64) not null unique references tile(id) on delete cascade,
  resolved_letter varchar(8) not null,
  constraint ux_board_cell_player_coords unique(player_id, x, y)
);

create table game_event (
  id bigint generated by default as identity primary key,
  room_id varchar(64) not null references game_room(id) on delete cascade,
  event_type varchar(32) not null,
  payload_json text not null,
  created_at timestamp with time zone not null,
  sequence_number bigint not null
);

create unique index ux_game_event_room_sequence on game_event(room_id, sequence_number);

create table game_snapshot (
  room_id varchar(64) primary key references game_room(id) on delete cascade,
  payload_json text not null,
  updated_at timestamp with time zone not null,
  version bigint not null
);

create table bandit_theme_selection (
  id varchar(64) primary key,
  room_id varchar(64) not null references game_room(id) on delete cascade,
  triggering_player_id varchar(64) not null references game_player(id) on delete cascade,
  selected_theme varchar(64),
  status varchar(16) not null,
  created_at timestamp with time zone not null,
  resolved_at timestamp with time zone,
  pending_placement_json text
);

create index ix_bandit_selection_room_status on bandit_theme_selection(room_id, status);
