create table room_chat_message (
  id bigint generated by default as identity primary key,
  room_id varchar(64) not null references game_room(id) on delete cascade,
  player_id varchar(64) not null references game_player(id) on delete cascade,
  message_text varchar(280) not null,
  created_at timestamp with time zone not null,
  sequence_number bigint not null
);

create unique index ux_room_chat_message_room_sequence on room_chat_message(room_id, sequence_number);
create index ix_room_chat_message_room_created on room_chat_message(room_id, created_at desc);
