package com.mixmo.common;

public enum EventType {
  ROOM_CREATED,
  PLAYER_JOINED,
  GAME_STARTED,
  GAME_STATE_UPDATED,
  PLACEMENT_CONFIRMED,
  BOARD_TILES_RETURNED,
  MIXMO_RESOLVED,
  STALE_GAME_WARNING_STARTED,
  STALE_GAME_WARNING_CLEARED,
  GAME_PAUSED,
  BANDIT_THEME_SELECTED,
  GAME_RESUMED,
  GAME_FINISHED,
  PLAYER_RECONNECTED
}
